---
# tasks file for myftp

    - name: Install vsftpd service
      yum: name=vsftpd state=latest

    - name: Start vsftpd service
      service: name=vsftpd state=started enabled=yes

    - name: Check service status
      service_facts:

    - debug:
        var: ansible_facts.services["vsftpd.service"].state

    # - name: Create index.html
    #   template:
    #     src: index.html.j2
    #     dest: /var/www/html/index.html
    #     mode: 0777

    # - name: Install firewalld
    #   yum: name=firewalld state=latest

    # - name: Start firewalld service
    #   service: name=firewalld state=started enabled=yes
   
    # - name: Open 80 port
    #   firewalld:
    #     service: http
    #     permanent: yes
    #     state: enabled
    #     immediate: yes