---
- name: Create users
  hosts: nodes
  vars_files:
    secret
  tasks:
    - name: Add new users
      user:
        name: "{{ item }}"
        password: "{{ upass | password_hash('sha512') }}"
        createhome: yes
        comment: "{{ item }}@example.com"
        state: present
      with_items:
        - "alice"
        - "bob"
        - "carol"
          